# Generated by Django 5.1.6 on 2025-02-21 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='answer_sheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('assigned_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sheets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
